/*****************************************************
* Class Name :
* Author     : Ankush Dubey
* Description: 
* Created Date: 
* Related Component : 
*/

public with sharing class WKSFDC_DeserializeResponse 
{
    
    
    public class NetSuiteApi {
        public String status;
        public String reference_id;
        public String prospectno;
        public String request_no;
        public String msg;
        
    
    public NetSuiteApi(){
            
    }
        
}
    
        

    
    
}